analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.6547177229076624
  brandStrength: 0.3696023277007043
  rhythmicContrast: 0.6506727712694556
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.908295176923275
purpose: []
favicon: null
name: ĭĭ Enterprises
typography_spectrum: 0.69693
