name: ĭĭ Enterprises
favicon: null
layout_spectrum: 0.86478
typography_spectrum: 0.69693
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ĭĭ Enterprises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3696023277007043
  lightness: 0.908295176923275
  saturation: 0.6547177229076624
  rhythmicContrast: 0.6506727712694556
purpose: []
